export enum ErrorCodes {
    CONFIG_FILE_NOT_FOUND = 'CONFIG_FILE_NOT_FOUND',
    CONFIG_FILE_INCORRECT_FORMAT = 'CONFIG_FILE_INCORRECT_FORMAT',
    SSH_PRIVATE_KEY_NOT_FOUND = 'SSH_PRIVATE_KEY_NOT_FOUND',
}
